[tools]
antigravity-cli = "latest"
aspire = "latest"
babashka = "latest"
claude = "latest"
codex = "latest"
dotnet = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }
gh = "latest"
"github:basecamp/hey-cli" = "latest"
node = "26.7.0"
"npm:@xai-official/grok" = "latest"
"npm:playwright" = "latest"
python = "latest"
ruby = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]

[settings.ruby]
compile = false
